# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
dataset_fields:
  - field_name: title
    label: Title
    datajson: title
  - field_name: organization
    label: Organization
    form_template: form/organization.html
    datajson: publisher.name
  - field_name: notes
    label: Description
    form_template: form/textarea.html
    datajson: description
  - field_name: abbreviations
    label: Abbreviations 
    datajson: abbreviations
  - field_name: category
    label: Category
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: constraints
    label: Constraints
    datajson: constraints
  - field_name: url
    label: URL
    datajson: url
  - field_name: primary_language
    label: Primary Language
    datajson: primary_language
  - field_name: supplier_contributers
    label: Supplier Contributers
    datajson: supplier_contributers
   - field_name: vendor_contributers
    label: Vendor Contribuers
    datajson: vendor_contributers
  - field_name: consumer_contributers
    label: Consumer Contributers
    datajson: consumer_contributers
  - field_name: independent_contributers
    label: Independent Contributers
    datajson: independent_contributers
   - field_name: maturity_level
    label: Maturity Level
    datajson: maturity_level
    - field_name: maturity_level

organization_fields:
  - field_name: title
    label: Title
  - field_name: description
    label: Description
  - field_name: logo
    label: Logo

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
