# To add fields, make a new schema file in this directory
# and change the schema setting in _config.yml to its name
datastandard_fields:
  - field_name: title
    label: Title
    datajson: title
    def: Full name of standard
    form_template: form/textarea.html
  - field_name: coordinator
    label: Coordinator
    form_template: form/coordinator.html
    datajson: publisher.name
  - field_name: publishing_entity
    label: Publishing Entity
    datajson: publishing_entity
    def: Entity which publishes the standard. This may be the same as the coordinating entitiy; it may be a standards organization such as ISO, IETF, W3C; or other. Name of organization, country of organization, URL of organization, name of contact, email address of contact
    form_template: form/textarea.html
  - field_name: notes
    label: Description
    datajson: description
    def: A brief description what the standard includes
    form_template: form/textarea.html
  - field_name: category
    label: Category
    form_template: form/category.html
    display_template: display/category.html
    datajson: category
  - field_name: abbreviations
    label: Abbreviations 
    datajson: abbreviations
    def: Abbreviation(s) by which the standard is also known
    form_template: form/textarea.html
  - field_name: constraints
    label: Constraints
    datajson: constraints
    def: A set of restrictions or situations which the standard might not address. (For example, Open Contracting isn’t compatible with some procurement laws)
    form_template: form/textarea.html
  - field_name: url
    label: URL
    datajson: url
    def: Internet address / landing page where the standard can be found
    form_template: form/textarea.html
  - field_name: primary_language
    label: Primary Language
    datajson: primary_language
    def: Written/Spoken language in which the standard is maintained
    form_template: form/textarea.html
  - field_name: supplier_contributers
    label: Supplier Contributers 
    datajson: supplier_contributers
    def: Number of data suppliers who formally participate in standards development
    form_template: form/textarea.html
  - field_name: vendor_contributers
    label: Vendor Contributers
    datajson: vendor_contributers
    def: Number of software vendors who formally participate in standards development
    form_template: form/textarea.html
  - field_name: consumer_contributers
    label: Consumer Contributers
    datajson: consumer_contributers
    def: Number of data consumers who formally participate in standards development
    form_template: form/textarea.html
  - field_name: independent_contributers
    label: Independent Contributers
    datajson: independent_contributers
    def: Number of contributors who neither supply nor consume data but participate in standards development (typically advisors, intermediaries, or conveners)
    form_template: form/textarea.html
  - field_name: maturity_level
    label: Maturity Level
    datajson: maturity_level
  - field_name: contributor_activity
    label: Contributor Activity
    datajson: contributor_activity
    def: Some measure of how often contributors participate in discussions about the standard
    form_template: form/textarea.html
  - field_name: estimated_supplier_market
    label: Estimated Supplier Market
    datajson: estimated_supplier_market
    def: Some measure of how many entities publish data compatible with the standard
    form_template: form/textarea.html
  - field_name: estimated_consumer_market
    label: Estimated Consumer Market
    datajson: estimated_consumer_market
    def: Some measure of how many organizations consume data using the standard
    form_template: form/textarea.html
  - field_name: estimated_vendor_market
    label: Estimated Vendor Market
    datajson: estimated_vendor_market
    def: Some measure of how many vendors provide software which natively supports importing and/or exporting data compatible with the standard
    form_template: form/textarea.html
  - field_name: latest_revision
    label: Latest Revision
    datajson: latest_revision
    def: Date of most recent major revision
    form_template: form/textarea.html
  - field_name: has_schematics
    label: Has Schematics
    datajson: has_schematics
  - field_name: has_extendable_schematics
    label: Has Extendable Schematics
    datajson: has_extendable_schematics
  - field_name: has_semantics
    label: Has Semantics
    datajson: has_semantics
  - field_name: has_test_tools
    label: Has Test Tools
    datajson: has_test_tools
  - field_name: has_sdks
    label: Has SDKs
    datajson: has_sdks
  - field_name: has_certification_mechanism
    label: Has Certification Mechanism
    datajson: has_certification_mechanism
  - field_name: has_support_resources
    label: Has Support Resources
    datajson: has_support_resources
  - field_name: is_free_to_use
    label: Is Free To Use
    datajson: is_free_to_use
  - field_name: is_open_to_contribute
    label: Is Open To Contribute
    datajson: is_open_to_contribute
  - field_name: has_sample_contract_language
    label: Has Sample Contract Language
    datajson: has_sample_contract_language
  - field_name: supports_api
    label: Supports API
    datajson: supports_api
  - field_name: supports_bulk_download
    label: Supports Bulk Download
    datajson: supports_bulk_download
  - field_name: has_geospatial_elements
    label: Has Geospatial Elements
    datajson: has_geospatial_elements
  - field_name: has_temporal_elements
    label: Has Temporal Elements
    datajson: has_temporal_elements

coordinator_fields:
  - field_name: title
    label: Title
    def: Name of coordinator
    form_template: form/textarea.html
  - field_name: country 
    label: Country
    def: Country of coordinator
    form_template: form/textarea.html
  - field_name: website
    label: Website
    def: URL of the website of a coordinator
    form_template: form/textarea.html
  - field_name: email
    label: E-mail 
    def: E-mail adress of contact
    form_template: form/textarea.html
  - field_name: logo
    label: Logo
    def: URL of an image of the coordinator
    form_template: form/textarea.html

category_fields:
  - field_name: name
    label: Name
  - field_name: logo
    label: Logo
  - field_name: logo_credit
    label: Logo Credit
  - field_name: featured
    label: Featured on Homepage
    form_template: form/checkbox.html
